///|
/// Screeps Arena raw 层的原始 JS 对象类型。
#external
pub type JsGameObject

///|
/// Screeps Arena raw 层的原始 Store 对象类型。
#external
pub type JsStore

///|
/// Screeps Arena raw 层的原始 spawn 结果对象类型。
#external
pub type JsSpawnCreepResult

///|
/// Screeps Arena raw 层的原始 spawning 对象类型。
#external
pub type JsSpawning

///|
/// Screeps Arena raw 层的原始 construction site 创建结果对象类型。
#external
pub type JsCreateConstructionSiteResult

///|
/// Screeps Arena raw 层的原始 Creep 对象类型。
#external
pub type JsCreep

///|
/// Screeps Arena raw 层的原始 creep body part 对象类型。
#external
pub type JsCreepBodyPart

///|
/// Screeps Arena raw 层的原始 Source 对象类型。
#external
pub type JsSource

///|
/// Screeps Arena raw 层的原始 Flag 对象类型。
#external
pub type JsFlag

///|
/// Screeps Arena raw 层的原始 StructureSpawn 对象类型。
#external
pub type JsStructureSpawn

///|
/// Screeps Arena raw 层的原始 StructureTower 对象类型。
#external
pub type JsStructureTower

///|
/// Screeps Arena raw 层的原始 StructureContainer 对象类型。
#external
pub type JsStructureContainer

///|
/// Screeps Arena raw 层的原始 ConstructionSite 对象类型。
#external
pub type JsConstructionSite
